language: java
install: skip

os: linux
jdk: oraclejdk11

services:
  - docker

script:
  - ./mvnw clean install -DskipTests
  - ./mvnw test -B

deploy:
  provider: script
  script: bash scripts/docker_push
  skip_cleanup: true
  on:
    branch: master
    tags: true