version: '3.1'
services:
  API:
    image: 'homeserver.jar'
    ports:
      - '8080:8080'
    depends_on:
      - PostgreSQL
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/homeserver
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password

  PostgreSQL:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=homeserver
    healthcheck:
      test: ['CMD-SHELL', "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  FrontEnd:
    image: wesselinktc/homeserver-fe
    ports:
      - '80:80'
    depends_on:
      - API