spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true